### PR TITLE
Add `scrollToMonth` and `jumpToMonth` inside `CleanCalendarController`

### PR DESCRIPTION
**Pull request by tatsuyuki25**
1. Add function `scrollToMonth` and `jumpToMonth` inside `CleanCalendarController`.
2. Add property `initialFocusDate` inside `CleanCalendarController`.
3. Remove property `scrollController`.

#29 #22

### CODE REVIEW

**Comment by CaioGrossi** [comment]
waiting for this merge ..

**Comment by kidmortal** [comment]
thats an absolute must have.

**Comment by CaioGrossi** [comment]
@tatsuyuki25 I'm trying to use the function "jumpToMonth" but it's not working

**Comment by FabioFiuza** [comment]
I will do review today this pull request 🤔

**Comment by rodrigodobbin** [comment]
Merge Done folks. And release 1.3.0 in pub.dev just published. 

Cya, and thanks for the PR @tatsuyuki25

**Pull request merged**
