### PR TITLE
aspectRatio property param added - days, weekdays widget

### PR DESCRIPTION
**Pull request by daybreaker42**
### About
In the current version, it is not possible to set the width/height of each element of the days widget and weekdays widget at all.
I added a `childAspectRatio` parameter to `days_widget.dart` and `weekdays_widget.dart` so that the developer can directly set the option.
And also `scrollable_clean_calendar.dart` needed to be added some parameter that I added, so I also changed it.

### Editted files
- `weekdays_widget.dart`
- `days_widget.dart`
- `scrollable_clean_calendar.dart`

### Relevent Issues
#51

### CODE REVIEW

**Comment by rodrigodobbin** [comment]
@siejwkaodj please update de Readme File, and add this two parameters there, so our users can know what our plugin has to offer.

And Thanks for your contribution.

**Comment by siejwkaodj** [comment]
@rodrigodobbin Sorry for the late reply. I checked the mentioned points and added them to README.md, so please check my new commits.

+ Also, I am not yet familiar with dart syntax, so when setting the default value for day/weekday aspectRatio, I use `childAspectRatio: aspectRatio ?? I set it as 1.0,` in each `days_widget.dart` and `weedkays_widget.dart`.
But I'm not sure if I should say that the `default value` is 1.0 in `README.md`. If there is any problem, it would be good to let me know further.

**Comment by rodrigodobbin** [comment]
@siejwkaodj i had to close this MR because it has conflict with master. But I open another one.

Next time dont use develop branch to copy from. Copy from Master (Main) branch.

**Comment by rodrigodobbin** [comment]
And to explain your doubt. 

When you don't know what to put as a default value, and if It can be Nullable or not. You have to see on the root file. 

On this cenario, you are using de count function of GridView. 
Captura de Tela 2024-02-15 às 11 17 35

So command + click on the function to open its properties. (if you are on windows or linux is ctrl + click)

then you will see the function inside the scroll_view.dart file wich is the file from the framework itself.

Then you will search for the property you are using, in this case `childAspectRatio` and check if it is nullable or have a default value. 

Captura de Tela 2024-02-15 às 11 22 09

Hope this explains it.

**Comment by siejwkaodj** [comment]
Thanks for explaining.

I used the develop branch because I thought there was an issue/PR saying to do a PR on the develop branch. But I couldn't find that issue so If there's anything I want to add in the future, I'll just do it in the main branch.

**Comment by rodrigodobbin** [comment]
The package is published https://pub.dev/packages/scrollable_clean_calendar

version 1.5.0 

@siejwkaodj

**Comment by daybreaker42** [comment]
Thank you for your kind reply.
I hope there will be many opportunities to create cool things using this library in the future.
Have a good day.

**Pull request closed without merging**
